### ISSUE TITLE
Make the background color transparent please.

### ISSUE THREAD

**Issue by mashirozx** [ai-genie/chatgpt-vscode#118]
### Describe the feature

the default background color is ugly with my theme:
![image](https://github.com/ai-genie/chatgpt-vscode/assets/16148054/f87b5425-d0fd-4923-a3f4-507a48e10e0d)

it should set to be transparent and use the `monaco-workbench`'s default background color:

![image](https://github.com/ai-genie/chatgpt-vscode/assets/16148054/283ebabf-755f-40bf-8583-b211a2b015c6)

Things need to be changed:

```css
body { background-color: transparent }
.input-background { background: #3a444980 } /* needs to add some opicaty */
```
